/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import config.PasswordUtils;
import config.config;
import config.session;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class loginform extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public loginform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        logo_font = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        reg_btn = reg_btn = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();

                // This makes the rounded edges smooth
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // This tells the code: "Use whatever color is already set for this panel"
                g2.setColor(getBackground());

                // This only paints the rounded area
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 5, 5);

                g2.dispose();
            }
        };

        reg_btn.setOpaque(false);
        ;
        jLabel2 = new javax.swing.JLabel();
        log_btn = log_btn = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();

                // This makes the rounded edges smooth
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // This tells the code: "Use whatever color is already set for this panel"
                g2.setColor(getBackground());

                // This only paints the rounded area
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 5, 5);

                g2.dispose();
            }
        };

        log_btn.setOpaque(false);
        ;
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField() {
            private String placeholder = "Email Address";

            @Override
            public void paint(java.awt.Graphics g) {
                super.paint(g);
                if (getText().isEmpty()) {
                    java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                    g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                    g2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
                    g2.setColor(java.awt.Color.BLACK);
                    java.awt.FontMetrics fm = g2.getFontMetrics();
                    int y = (getHeight() - fm.getHeight()) / 2 + fm.getAscent();
                    g2.drawString(placeholder, 10, y);
                    g2.dispose();
                }
            }
        };
        password = new javax.swing.JPasswordField() {
            private String placeholder = "Password";

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);

                if (getPassword().length == 0) {
                    java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                    g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                    // 1. SET FONT: Segoe UI, Bold, Size 16 (adjust size as needed)
                    g2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));

                    // 2. SET COLOR: Solid Black
                    g2.setColor(java.awt.Color.BLACK); 

                    // 3. ALIGNMENT logic
                    java.awt.FontMetrics fm = g2.getFontMetrics();
                    int y = (getHeight() - fm.getHeight()) / 2 + fm.getAscent();

                    g2.drawString(placeholder, 10, y);
                    g2.dispose();
                }
            }
        };
        jLabel6 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(26, 26, 26));
        header.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 153, 255), null, new java.awt.Color(102, 102, 102)));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_font.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        logo_font.setForeground(new java.awt.Color(255, 255, 255));
        logo_font.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_font.setText("MOTOR-PARTS");
        header.add(logo_font, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 80));

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        header.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 80));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 505, 80));

        body.setBackground(new java.awt.Color(0, 0, 0));
        body.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 153, 255), new java.awt.Color(51, 153, 255), null, new java.awt.Color(102, 102, 102)));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reg_btn.setBackground(new java.awt.Color(26, 26, 26));
        reg_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true));
        reg_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reg_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reg_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reg_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reg_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reg_btnMousePressed(evt);
            }
        });
        reg_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTER");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reg_btn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, -1));

        body.add(reg_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 190, 50));

        log_btn.setBackground(new java.awt.Color(31, 161, 216));
        log_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        log_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                log_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                log_btnMousePressed(evt);
            }
        });
        log_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOGIN");
        log_btn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 70, -1));

        body.add(log_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 190, 50));

        email.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true));
        body.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 430, 50));

        password.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        body.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 430, 50));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Login Here!");
        body.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log-reg.png"))); // NOI18N
        body.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 503, 358));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 505, 358));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void log_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_btnMouseClicked
            String Email = email.getText();
String Password = password.getText();

if (Email.isEmpty() || Password.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please fill in all fields!");
    return;
}

// Hash the entered password
String hashedPassword = PasswordUtils.hashPassword(Password);

String sql = "SELECT id, email, address, status, type FROM users WHERE email = ? AND password = ?";

String status = null;
String userType = null;

try (
    java.sql.Connection conn = config.connectDB();
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
) {
    pst.setString(1, Email);
    pst.setString(2, hashedPassword); // compare hashed password

    java.sql.ResultSet rs = pst.executeQuery();

    if (!rs.next()) {
        JOptionPane.showMessageDialog(null, "Invalid email or password!");
        return;
    }

    status = rs.getString("status");
    userType = rs.getString("type");

    session.setSession(
        rs.getInt("id"),
        rs.getString("email"),
        rs.getString("address"),
        userType
    );

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Login Error: " + e.getMessage());
    return;
}

// Check account status
if (!status.equalsIgnoreCase("Active")) {
    JOptionPane.showMessageDialog(
        null,
        "Your account is inactive. Please contact the administrator."
    );
    return;
}

JOptionPane.showMessageDialog(null, "LOGIN SUCCESS!");

// Open dashboard based on user type
if (userType.equalsIgnoreCase("Admin")) {
    new AdminDashboard().setVisible(true);
} else if (userType.equalsIgnoreCase("User")) {
    new userdashboard().setVisible(true);
}

dispose(); 
    }//GEN-LAST:event_log_btnMouseClicked

    private void reg_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_btnMouseClicked
       registerform rm = new registerform();
       rm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_reg_btnMouseClicked

    private void reg_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_btnMousePressed
    reg_btn.setBackground(new java.awt.Color(21, 125, 169));
    }//GEN-LAST:event_reg_btnMousePressed

    private void log_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_btnMouseEntered
        log_btn.setBackground(new java.awt.Color(66, 191, 245));
    }//GEN-LAST:event_log_btnMouseEntered

    private void log_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_btnMouseExited
         log_btn.setBackground(new java.awt.Color(31, 161, 216));
    }//GEN-LAST:event_log_btnMouseExited

    private void log_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_btnMousePressed
      log_btn.setBackground(new java.awt.Color(21, 125, 169));
    }//GEN-LAST:event_log_btnMousePressed

    private void reg_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_btnMouseExited
       reg_btn.setBackground(new java.awt.Color(26, 26, 26));
    }//GEN-LAST:event_reg_btnMouseExited

    private void reg_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_btnMouseEntered
      reg_btn.setBackground(new java.awt.Color(66, 191, 245));
    }//GEN-LAST:event_reg_btnMouseEntered

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new loginform().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JLabel background;
    private javax.swing.JPanel body;
    private javax.swing.JTextField email;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel log_btn;
    private javax.swing.JLabel logo_font;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel reg_btn;
    // End of variables declaration//GEN-END:variables
}
